#!/bin/bash

if [ "" = "$BASH_SOURCE" ]; then
  export JENV_WORKING_DIR=$(dirname $0)
else
  export JENV_WORKING_DIR=$(dirname $BASH_SOURCE)
fi
source $JENV_WORKING_DIR/logging.sh
source $JENV_WORKING_DIR/create.sh
source $JENV_WORKING_DIR/list.sh
source $JENV_WORKING_DIR/use.sh
source $JENV_WORKING_DIR/scripts.sh
source $JENV_WORKING_DIR/usage.sh

_jenv_edit () {
    _jenv_env_dir=${JENV_DEV_ENV_DIR:-~/.dev_envs/}
    if [ "" != "$1" ]; then # TODO: if current env is set edit that
        # Edit implementation
        :
    else
        _log_line ERROR "Must supply an environment name as an argument"
        _log_line INFO "-------------------"
        find $_jenv_env_dir* -type d -maxdepth 0 -exec basename {} \;
        _log_line INFO "-------------------"
    fi
}

_jenv_get_color_for_prompt () {
  echo "\033[$1m"
}

jenv_get_prompt () {
  if [ "" = "$CURRENT_DEV_VIRTUAL_ENVIRONMENT" ]; then
    echo ""
  else
    echo "[$CURRENT_DEV_VIRTUAL_ENVIRONMENT] "
  fi
}

jenv_prepend_to_prompt () {
  export PROMPT=$(_jenv_get_color_for_prompt 35)'$(jenv_get_prompt)'$PROMPT
}

_jenv_current () {
  echo $CURRENT_DEV_VIRTUAL_ENVIRONMENT
}

jenv () {
  ## Plans
  ##
  ## docs     - A docs dir that lets you store notes
  ## Describe - describe an environment (print out all its stuffs)

  case $1 in
    "create")
      _jenv_create ${@:2}
      ;;
    "use")
      _jenv_use ${@:2}
      ;;
    "unuse")
      _jenv_unuse ${@:2}
      ;;
    "ls" | "list")
      _jenv_list ${@:2}
      ;;
    "current")
      _jenv_current ${@:2}
      ;;
    "run")
      _jenv_run_script ${@:2}
      ;;
    "view")
      _jenv_view_script ${@:2}
      ;;
    *)
      _jenv_usage ${@:2}
      ;;
  esac
}